alter table COVIDHELPER_DIAGNOSIS add constraint FK_COVIDHELPER_DIAGNOSIS_ON_DOCTOR foreign key (DOCTOR_ID) references COVIDHELPER_DOCTOR(ID);
alter table COVIDHELPER_DIAGNOSIS add constraint FK_COVIDHELPER_DIAGNOSIS_ON_PATIENT foreign key (PATIENT_ID) references COVIDHELPER_PATIENT(ID);
create index IDX_COVIDHELPER_DIAGNOSIS_ON_DOCTOR on COVIDHELPER_DIAGNOSIS (DOCTOR_ID);
create index IDX_COVIDHELPER_DIAGNOSIS_ON_PATIENT on COVIDHELPER_DIAGNOSIS (PATIENT_ID);
